# Generated by Django 4.2.16 on 2026-06-26 20:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('week_of', models.DateField()),
                ('mood', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('wins', models.TextField(blank=True, default='')),
                ('blockers', models.TextField(blank=True, default='')),
                ('learning', models.TextField(blank=True, default='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'checkin',
                'ordering': ['-week_of'],
            },
        ),
        migrations.CreateModel(
            name='ManagerResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('reaction', models.CharField(blank=True, default='', max_length=8)),
                ('follow_up', models.BooleanField(default=False)),
                ('add_to_one_on_one', models.BooleanField(default=False)),
                ('check_in', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='checkins.checkin')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_responses', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'checkin_manager_response',
                'indexes': [models.Index(fields=['tenant', 'check_in'], name='ix_checkinresp_card')],
            },
        ),
        migrations.CreateModel(
            name='CheckInPriority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('text', models.CharField(max_length=280)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DONE', 'Done'), ('CARRY_FORWARD', 'Carry forward')], default='ACTIVE', max_length=16)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to='checkins.checkin')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'checkin_priority',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['tenant', 'check_in'], name='ix_checkinprio_card')],
            },
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['tenant', 'author', '-week_of'], name='ix_checkin_author_recent'),
        ),
        migrations.AddConstraint(
            model_name='checkin',
            constraint=models.UniqueConstraint(fields=('author', 'week_of'), name='uniq_checkin_author_week'),
        ),
    ]
