# Generated by Django 4.2.16 on 2026-06-12 20:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('agent_code', models.CharField(default='all', max_length=32)),
                ('window', models.CharField(choices=[('DAILY', 'Daily'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=8)),
                ('limit', models.PositiveIntegerField()),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'billing_agent_budget',
                'ordering': ['agent_code', 'window'],
            },
        ),
        migrations.CreateModel(
            name='TokenLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('agent_code', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=64)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('occurred_at', models.DateTimeField()),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'billing_token_ledger',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['tenant', 'agent_code', '-occurred_at'], name='ix_ledger_tenant_agent')],
            },
        ),
        migrations.AddConstraint(
            model_name='agentbudget',
            constraint=models.UniqueConstraint(fields=('tenant', 'agent_code', 'window'), name='uq_agentbudget_tenant_agent_window'),
        ),
    ]
