# Generated by Django 4.2.16 on 2026-06-12 21:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('kind', models.CharField(choices=[('JIRA', 'Jira'), ('SLACK', 'Slack')], max_length=8)),
                ('enabled', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('secret_ref', models.CharField(blank=True, max_length=128)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'integrations_tenant_integration',
                'ordering': ['kind'],
            },
        ),
        migrations.AddConstraint(
            model_name='tenantintegration',
            constraint=models.UniqueConstraint(fields=('tenant', 'kind'), name='uq_integration_tenant_kind'),
        ),
    ]
