# Generated by Django 4.2.16 on 2026-06-21 16:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
        ('identity', '0002_user_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamlIdpConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('idp_entity_id', models.CharField(max_length=255)),
                ('idp_sso_url', models.URLField(max_length=512)),
                ('idp_x509_cert', models.TextField(help_text='IdP signing certificate (PEM body / base64). Public — used to verify assertion signatures.')),
                ('email_attribute', models.CharField(blank=True, default='email', max_length=128)),
                ('role_attribute', models.CharField(blank=True, default='role', max_length=128)),
                ('role_map', models.JSONField(blank=True, default=dict)),
                ('sp_private_key_secret_ref', models.CharField(blank=True, default='', max_length=128)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'identity_saml_idp_config',
            },
        ),
        migrations.AddConstraint(
            model_name='samlidpconfig',
            constraint=models.UniqueConstraint(fields=('tenant',), name='uq_saml_config_tenant'),
        ),
    ]
