# Generated by Django 4.2.16 on 2026-07-12 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
        ('identity', '0003_samlidpconfig_samlidpconfig_uq_saml_config_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('event', models.CharField(choices=[('LOGIN_OK', 'Login succeeded'), ('LOGIN_FAILED', 'Login failed'), ('LOCKOUT', 'Locked out (too many attempts)'), ('MFA_FAILED', 'MFA code rejected'), ('LOGOUT', 'Logged out'), ('SESSION_REVOKED', 'Session revoked'), ('PASSWORD_CHANGED', 'Password changed')], max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identity_login_event',
                'indexes': [models.Index(fields=['tenant', 'user', '-created_at'], name='identity_lo_tenant__11c284_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('last_seen', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identity_device_session',
                'indexes': [models.Index(fields=['tenant', 'user', '-last_seen'], name='identity_de_tenant__0c7ead_idx')],
            },
        ),
    ]
