# Generated by Django 4.2.16 on 2026-07-12 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
        ('identity', '0005_user_department_user_employee_id_user_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager'), ('HRBP', 'HRBP'), ('ADMIN', 'Admin')], default='EMPLOYEE', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REVOKED', 'Revoked')], default='PENDING', max_length=10)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'identity_invitation',
                'indexes': [models.Index(fields=['tenant', 'status', '-created_at'], name='identity_in_tenant__22f086_idx')],
            },
        ),
    ]
