# Generated by Django 4.2.16 on 2026-08-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_invitation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant', 'display_name'], name='ix_user_tenant_dispname'),
        ),
    ]
