# Generated by Django 4.2.16 on 2026-08-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_user_ix_user_tenant_dispname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='erased_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
