# Generated by Django 4.2.16 on 2026-06-10 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        ('tenancy', '0001_initial'),
        ('cycles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=255)),
                ('criticality', models.CharField(choices=[('HIGH', 'High'), ('CRITICAL', 'Critical')], default='HIGH', max_length=8)),
                ('knowledge_risk', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=8)),
                ('risk_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=8)),
                ('incumbent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='critical_roles_held', to=settings.AUTH_USER_MODEL)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='critical_roles_marked', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='org.position')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'succession_critical_role',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NineBoxPlacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('performance_band', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=8)),
                ('potential_band', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=8)),
                ('box', models.PositiveSmallIntegerField()),
                ('assessed_at', models.DateTimeField()),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ninebox_assessments', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ninebox_placements', to='cycles.performancecycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ninebox_placements', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'succession_ninebox',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='BenchCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('readiness', models.CharField(choices=[('READY_NOW', 'Ready now'), ('READY_SOON', 'Ready soon'), ('DEVELOPING', 'Developing'), ('NOT_READY', 'Not ready')], default='NOT_READY', max_length=12)),
                ('readiness_overridden', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bench_candidates_added', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bench_entries', to=settings.AUTH_USER_MODEL)),
                ('critical_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bench', to='succession.criticalrole')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'succession_bench_candidate',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuccessionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_HUMAN_REVIEW', 'Pending human review'), ('PUBLISHED', 'Published')], default='PENDING_HUMAN_REVIEW', max_length=24)),
                ('ranked_bench', models.JSONField(default=list)),
                ('coverage_status', models.CharField(choices=[('RED', 'Red (inadequate)'), ('AMBER', 'Amber'), ('GREEN', 'Green')], max_length=8)),
                ('red_flags', models.JSONField(default=list)),
                ('action_items', models.JSONField(default=list)),
                ('source', models.CharField(choices=[('DETERMINISTIC', 'Deterministic engine'), ('AI', 'Agent 4 (Module 10)')], default='DETERMINISTIC', max_length=16)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('generated_at', models.DateTimeField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('critical_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='succession.criticalrole')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='succession_plans_reviewed', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'succession_plan',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='ix_succplan_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='nineboxplacement',
            constraint=models.UniqueConstraint(fields=('tenant', 'employee', 'cycle'), name='uq_ninebox_emp_cycle'),
        ),
        migrations.AddIndex(
            model_name='criticalrole',
            index=models.Index(fields=['tenant', 'status'], name='ix_critrole_status'),
        ),
        migrations.AddConstraint(
            model_name='benchcandidate',
            constraint=models.UniqueConstraint(fields=('tenant', 'critical_role', 'candidate'), name='uq_bench_role_candidate'),
        ),
    ]
