# Generated by Django 4.2.16 on 2026-06-21 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('succession', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nineboxplacement',
            name='override_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nineboxplacement',
            name='override_box',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nineboxplacement',
            name='override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ninebox_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nineboxplacement',
            name='override_rationale',
            field=models.TextField(blank=True),
        ),
    ]
