# Generated by Django 4.2.16 on 2026-06-10 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approvals', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JDVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('version_number', models.PositiveIntegerField()),
                ('body', models.JSONField(default=dict)),
                ('inputs_snapshot', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('citations', models.JSONField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jd_versions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jd_version',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('title', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=64)),
                ('department', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_HUMAN_REVIEW', 'Pending human review'), ('IN_REVIEW', 'In approval route'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=24)),
                ('source', models.CharField(choices=[('MANUAL', 'Manually authored'), ('AI', 'AI generated (Module 10)')], default='MANUAL', max_length=8)),
                ('approval_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='approvals.approvalroute')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jds_created', to=settings.AUTH_USER_MODEL)),
                ('current_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jd.jdversion')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'jd_jobdescription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='jdversion',
            name='jd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='jd.jobdescription'),
        ),
        migrations.AddField(
            model_name='jdversion',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.CreateModel(
            name='JDTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('role_family', models.CharField(max_length=128)),
                ('title_pattern', models.CharField(max_length=255)),
                ('level', models.CharField(blank=True, max_length=64)),
                ('default_body', models.JSONField(default=dict)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'jd_template',
                'ordering': ['role_family', 'title_pattern'],
            },
        ),
        migrations.CreateModel(
            name='JDRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('title', models.CharField(max_length=255)),
                ('level', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FULFILLED', 'Fulfilled'), ('DECLINED', 'Declined')], default='OPEN', max_length=12)),
                ('fulfilled_jd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilling_requests', to='jd.jobdescription')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jd_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'jd_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='jobdescription',
            index=models.Index(fields=['tenant', 'status'], name='ix_jd_status'),
        ),
        migrations.AddIndex(
            model_name='jobdescription',
            index=models.Index(fields=['tenant', 'title', 'level'], name='ix_jd_title_level'),
        ),
        migrations.AddConstraint(
            model_name='jdversion',
            constraint=models.UniqueConstraint(fields=('tenant', 'jd', 'version_number'), name='uq_jdversion_jd_number'),
        ),
    ]
