# Generated by Django 4.2.16 on 2026-06-10 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('artifact_type', models.CharField(max_length=64)),
                ('artifact_id', models.UUIDField()),
                ('mode', models.CharField(max_length=12)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated')], default='IN_PROGRESS', max_length=12)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_routes_initiated', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'approvals_route',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=255)),
                ('artifact_type', models.CharField(max_length=64)),
                ('mode', models.CharField(choices=[('SEQUENTIAL', 'Sequential'), ('PARALLEL', 'Parallel')], default='SEQUENTIAL', max_length=12)),
                ('active', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'approvals_workflow',
                'ordering': ['artifact_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStepInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('order', models.PositiveIntegerField()),
                ('approver_role', models.CharField(blank=True, max_length=16, null=True)),
                ('required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=12)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('timeout_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('escalation_role', models.CharField(blank=True, max_length=16, null=True)),
                ('escalated', models.BooleanField(default=False)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_step_instances', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('escalation_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_step_escalation_targets', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_instances', to='approvals.approvalroute')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'approvals_stepinstance',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('order', models.PositiveIntegerField()),
                ('approver_kind', models.CharField(choices=[('ROLE', 'Role'), ('NAMED', 'Named user')], max_length=8)),
                ('approver_role', models.CharField(blank=True, max_length=16, null=True)),
                ('required', models.BooleanField(default=True)),
                ('timeout_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('escalation_role', models.CharField(blank=True, max_length=16, null=True)),
                ('approver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps_named', to=settings.AUTH_USER_MODEL)),
                ('escalation_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps_escalation', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approvals.approvalworkflow')),
            ],
            options={
                'db_table': 'approvals_step',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='approvalroute',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='approvals.approvalworkflow'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['tenant', 'artifact_type', 'active'], name='ix_wf_active'),
        ),
        migrations.AddIndex(
            model_name='approvalstepinstance',
            index=models.Index(fields=['tenant', 'status', 'due_at'], name='ix_stepinst_due'),
        ),
        migrations.AddIndex(
            model_name='approvalstepinstance',
            index=models.Index(fields=['tenant', 'approver', 'status'], name='ix_stepinst_inbox'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.UniqueConstraint(fields=('tenant', 'workflow', 'order'), name='uq_step_workflow_order'),
        ),
        migrations.AddIndex(
            model_name='approvalroute',
            index=models.Index(fields=['tenant', 'artifact_type', 'artifact_id', 'status'], name='ix_route_artifact'),
        ),
    ]
