# Generated by Django 4.2.16 on 2026-06-10 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COLLECTING', 'Collecting'), ('CLOSED', 'Closed')], default='DRAFT', max_length=16)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('min_volume', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_cycles_opened', to=settings.AUTH_USER_MODEL)),
                ('performance_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_cycles', to='cycles.performancecycle')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_cycles', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'feedback_cycle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OneOnOneNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('body', models.TextField()),
                ('meeting_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='one_on_ones_attended', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='one_on_ones_led', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'feedback_oneonone',
                'ordering': ['-meeting_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('sections', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING_HUMAN_REVIEW', 'Pending human review'), ('HRBP_HOLD', 'Held for HRBP'), ('APPROVED', 'Approved'), ('RELEASED', 'Released')], default='PENDING_HUMAN_REVIEW', max_length=24)),
                ('anonymity_passed', models.BooleanField(default=True)),
                ('sensitive', models.BooleanField(default=False)),
                ('volume_total', models.PositiveIntegerField(default=0)),
                ('insufficient_groups', models.JSONField(blank=True, default=list)),
                ('insufficient_volume', models.BooleanField(default=False)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('generated_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='feedback.feedbackcycle')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_summaries_reviewed', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_summaries', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'feedback_summary',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('relationship', models.CharField(choices=[('SELF', 'Self'), ('MANAGER', 'Manager'), ('PEER', 'Peer'), ('UPWARD', 'Upward')], max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('DECLINED', 'Declined')], default='PENDING', max_length=12)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='feedback.feedbackcycle')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'feedback_request',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('relationship', models.CharField(choices=[('SELF', 'Self'), ('MANAGER', 'Manager'), ('PEER', 'Peer'), ('UPWARD', 'Upward')], max_length=8)),
                ('kind', models.CharField(choices=[('THREE_SIXTY', '360 cycle feedback'), ('CONTINUOUS', 'Continuous feedback')], max_length=16)),
                ('body', models.TextField()),
                ('sentiment', models.CharField(blank=True, max_length=16, null=True)),
                ('giver_marked_sensitive', models.BooleanField(default=False)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='feedback.feedbackcycle')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_given', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_received', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'feedback_item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='feedbacksummary',
            constraint=models.UniqueConstraint(fields=('tenant', 'cycle'), name='uq_summary_cycle'),
        ),
        migrations.AddConstraint(
            model_name='feedbackrequest',
            constraint=models.UniqueConstraint(fields=('tenant', 'cycle', 'giver'), name='uq_request_cycle_giver'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['tenant', 'subject', 'kind'], name='ix_feedback_subject'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('tenant', 'cycle', 'giver'), name='uq_feedback_cycle_giver'),
        ),
    ]
