# Generated by Django 4.2.16 on 2026-06-26 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('value', models.CharField(max_length=40)),
                ('message', models.TextField(max_length=1000)),
                ('badge', models.CharField(blank=True, default='', max_length=40)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private (just the two of us)'), ('MANAGER_ONLY', 'Manager only'), ('TEAM', 'Team'), ('COMPANY', 'Company')], default='TEAM', max_length=16)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognitions_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognitions_sent', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'recognition',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecognitionReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('emoji', models.CharField(max_length=8)),
                ('recognition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='recognition.recognition')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recognition_reaction',
                'indexes': [models.Index(fields=['tenant', 'recognition'], name='ix_recogreact_card')],
            },
        ),
        migrations.AddConstraint(
            model_name='recognitionreaction',
            constraint=models.UniqueConstraint(fields=('recognition', 'user', 'emoji'), name='uniq_recognition_reaction'),
        ),
        migrations.AddIndex(
            model_name='recognition',
            index=models.Index(fields=['tenant', '-created_at'], name='ix_recog_tenant_recent'),
        ),
        migrations.AddIndex(
            model_name='recognition',
            index=models.Index(fields=['tenant', 'recipient'], name='ix_recog_recipient'),
        ),
        migrations.AddIndex(
            model_name='recognition',
            index=models.Index(fields=['tenant', 'sender'], name='ix_recog_sender'),
        ),
    ]
