# Generated by Django 4.2.16 on 2026-06-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
