# Generated by Django 4.2.16 on 2026-06-10 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenancy', '0001_initial'),
        ('jd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open (vacancy)'), ('FILLED', 'Filled'), ('CLOSED', 'Closed')], default='OPEN', max_length=8)),
                ('opened_at', models.DateTimeField()),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions_created', to=settings.AUTH_USER_MODEL)),
                ('filled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_positions', to=settings.AUTH_USER_MODEL)),
                ('published_jd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jd.jobdescription')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_positions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'org_position',
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='ix_position_status'), models.Index(fields=['tenant', 'reports_to'], name='ix_position_reports_to')],
            },
        ),
    ]
