# Generated by Django 4.2.16 on 2026-06-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aijob',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
