# Generated by Django 4.2.16 on 2026-07-02 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0003_aijob_result_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_chat_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'ai_chat_session',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ChatPlanStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('ordinal', models.PositiveSmallIntegerField()),
                ('action', models.CharField(max_length=48)),
                ('feel', models.CharField(choices=[('confirm', 'Confirm in chat'), ('navigate', 'Open a screen'), ('clarify', 'Ask a question')], default='confirm', max_length=10)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True, default='')),
                ('reason', models.TextField(blank=True, default='')),
                ('preview', models.JSONField(blank=True, default=list)),
                ('deeplink', models.CharField(blank=True, default='', max_length=255)),
                ('prefill', models.JSONField(blank=True, default=dict)),
                ('candidates', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved (executing)'), ('done', 'Done'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ai.chatplan')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'ai_chat_plan_step',
                'ordering': ['ordinal'],
            },
        ),
        migrations.AddField(
            model_name='chatplan',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='ai.chatsession'),
        ),
        migrations.AddField(
            model_name='chatplan',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.CreateModel(
            name='ChatTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('text', models.TextField(blank=True, default='')),
                ('refs', models.JSONField(blank=True, default=list)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai.chatplan')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='ai.chatsession')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'ai_chat_turn',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['tenant', 'session', 'created_at'], name='ix_chatturn_session')],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['tenant', 'owner', '-last_activity'], name='ix_chatsess_owner'),
        ),
        migrations.AddConstraint(
            model_name='chatplanstep',
            constraint=models.UniqueConstraint(fields=('plan', 'ordinal'), name='uq_planstep_plan_ordinal'),
        ),
        migrations.AddIndex(
            model_name='chatplan',
            index=models.Index(fields=['tenant', 'owner', '-created_at'], name='ix_chatplan_owner'),
        ),
    ]
