# Generated by Django 4.2.16 on 2026-08-16 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0004_chatplan_chatsession_chatplanstep_chatplan_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantAIConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('provider', models.CharField(blank=True, choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('groq', 'Groq')], default='', max_length=16)),
                ('api_key_encrypted', models.TextField(blank=True, default='')),
                ('key_last4', models.CharField(blank=True, default='', max_length=4)),
                ('key_set_at', models.DateTimeField(blank=True, null=True)),
                ('model_overrides', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('key_set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'ai_tenant_config',
            },
        ),
        migrations.AddConstraint(
            model_name='tenantaiconfig',
            constraint=models.UniqueConstraint(fields=('tenant',), name='uq_ai_config_tenant'),
        ),
    ]
