# Generated by Django 4.2.16 on 2026-06-12 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenancy', '0001_initial'),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentRoadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=12)),
                ('tiers', models.JSONField(default=list)),
                ('skill_gap', models.JSONField(default=dict)),
                ('source', models.CharField(choices=[('DETERMINISTIC', 'Deterministic engine'), ('AI', 'Career Roadmap agent (Module 10)')], default='DETERMINISTIC', max_length=16)),
                ('advisory', models.BooleanField(default=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('generated_at', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_roadmaps', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmaps_generated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'career_development_roadmap',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='TargetRoleSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('selected_at', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_target_selections', to=settings.AUTH_USER_MODEL)),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_targets_selected', to=settings.AUTH_USER_MODEL)),
                ('target_jd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jd.jobdescription')),
                ('target_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='org.position')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'career_target_selection',
                'ordering': ['-selected_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('tier_index', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done')], default='NOT_STARTED', max_length=12)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='career.developmentroadmap')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_progress_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'career_roadmap_progress',
                'ordering': ['tier_index'],
            },
        ),
        migrations.AddField(
            model_name='developmentroadmap',
            name='selection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmaps', to='career.targetroleselection'),
        ),
        migrations.AddField(
            model_name='developmentroadmap',
            name='target_jd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jd.jobdescription'),
        ),
        migrations.AddField(
            model_name='developmentroadmap',
            name='target_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='org.position'),
        ),
        migrations.AddField(
            model_name='developmentroadmap',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='targetroleselection',
            index=models.Index(fields=['tenant', 'employee'], name='ix_career_target_emp'),
        ),
        migrations.AddConstraint(
            model_name='roadmapprogress',
            constraint=models.UniqueConstraint(fields=('tenant', 'roadmap', 'tier_index'), name='uq_progress_roadmap_tier'),
        ),
        migrations.AddIndex(
            model_name='developmentroadmap',
            index=models.Index(fields=['tenant', 'employee', 'status'], name='ix_roadmap_emp_status'),
        ),
        migrations.AddConstraint(
            model_name='developmentroadmap',
            constraint=models.CheckConstraint(check=models.Q(('advisory', True)), name='ck_roadmap_advisory_always_true'),
        ),
    ]
