# Generated by Django 4.2.16 on 2026-06-10 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('AI_DRAFTING', 'AI drafting'), ('PENDING_HUMAN_REVIEW', 'Pending human review'), ('EDITING', 'Editing'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FINALIZED', 'Finalized')], default='DRAFT', max_length=24)),
                ('draft_body', models.TextField(blank=True)),
                ('final_body', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual draft'), ('AI', 'AI draft (Agent 1)')], default='MANUAL', max_length=8)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('citations', models.JSONField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='cycles.performancecycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('human_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews_approved', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_authored', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'reviews_review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewStateTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('from_state', models.CharField(max_length=24)),
                ('to_state', models.CharField(max_length=24)),
                ('at', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_transitions', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='reviews.review')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'reviews_statetransition',
                'ordering': ['at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('assessment_type', models.CharField(choices=[('SELF', 'Self'), ('MANAGER', 'Manager'), ('PEER', 'Peer'), ('UPWARD', 'Upward')], max_length=8)),
                ('body', models.TextField()),
                ('submitted_at', models.DateTimeField()),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments_given', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='reviews.review')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'reviews_assessment',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='reviewassessment',
            constraint=models.UniqueConstraint(fields=('tenant', 'review', 'assessor'), name='uq_assessment_review_assessor'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['tenant', 'cycle', 'state'], name='ix_review_cycle_state'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('tenant', 'employee', 'cycle'), name='uq_review_tenant_emp_cycle'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('state', 'FINALIZED'), _negated=True), ('human_reviewer__isnull', False), _connector='OR'), name='ck_review_finalized_has_reviewer'),
        ),
    ]
