# Generated by Django 4.2.16 on 2026-06-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_approval_route'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['tenant', '-created_at'], name='ix_review_tenant_recent'),
        ),
    ]
