# Generated by Django 4.2.16 on 2026-06-21 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenancy', '0001_initial'),
        ('reviews', '0003_review_ix_review_tenant_recent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('section', models.CharField(blank=True, choices=[('SUMMARY', 'Summary'), ('STRENGTHS', 'Strengths'), ('DEVELOPMENT', 'Development'), ('GOALS', 'Goals'), ('RECOMMENDATIONS', 'Recommendations')], max_length=20, null=True)),
                ('body', models.TextField()),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reviews.reviewcomment')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.review')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'reviews_comment',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['tenant', 'review', 'created_at'], name='ix_reviewcomment_review')],
            },
        ),
    ]
