# Generated by Django 4.2.16 on 2026-06-09 21:15

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ACHIEVED', 'Achieved'), ('MISSED', 'Missed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_goals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_goals', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='cycles.performancecycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'goals_goal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('direction', models.CharField(choices=[('INCREASING', 'Higher is better'), ('DECREASING', 'Lower is better')], default='INCREASING', max_length=16)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual entry'), ('JIRA', 'Jira')], default='MANUAL', max_length=16)),
                ('external_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='goals.goal')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'goals_kpi',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KpiTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('role', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('direction', models.CharField(choices=[('INCREASING', 'Higher is better'), ('DECREASING', 'Lower is better')], default='INCREASING', max_length=16)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('default_weight', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'goals_kpitemplate',
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CycleScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('raw_score', models.DecimalField(decimal_places=4, max_digits=10)),
                ('z_score', models.DecimalField(decimal_places=4, max_digits=10)),
                ('t_score', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cohort_size', models.PositiveIntegerField()),
                ('cohort_key', models.CharField(default='tenant', max_length=64)),
                ('insufficient_cohort', models.BooleanField(default=False)),
                ('risk_status', models.CharField(choices=[('ON_TRACK', 'On track'), ('AT_RISK', 'At risk'), ('CRITICAL', 'Critical')], default='ON_TRACK', max_length=16)),
                ('pace_behind', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField()),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='cycles.performancecycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_scores', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'goals_cyclescore',
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='KpiMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('recorded_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('MANUAL', 'Manual entry'), ('JIRA', 'Jira'), ('SYSTEM', 'System')], default='MANUAL', max_length=16)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='goals.kpi')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_measurements', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'goals_kpimeasurement',
                'ordering': ['-recorded_at', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'kpi', '-recorded_at'], name='ix_meas_latest')],
            },
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['tenant', 'cycle', 'employee'], name='ix_goal_cohort'),
        ),
        migrations.AddConstraint(
            model_name='cyclescore',
            constraint=models.UniqueConstraint(fields=('tenant', 'employee', 'cycle'), name='uq_cyclescore_tenant_emp_cycle'),
        ),
    ]
