# Generated by Django 4.2.16 on 2026-06-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['tenant', 'employee', '-created_at'], name='ix_goal_emp_recent'),
        ),
    ]
