# Generated by Django 4.2.16 on 2026-06-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_ix_goal_emp_recent'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
